# 项目相关配置
manage:
  name: Manage
  version: 1.0.0
  copyrightYear: 2050
  # 实例演示开关
  demoEnabled: false
  profile: D:/manage/uploadPath
  addressEnabled: false
  captchaType: math

server:
  port: 9001
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.icss: debug
    org.springframework: warn

spring:
  key: 1985548800000
  messages:
    basename: i18n/messages
  profiles:
    active: druid
  servlet:
     multipart:
       max-file-size:  100000MB
       max-request-size:  200000MB
  data:
    redis:
      host: 60.205.229.98
      port: 6379
      database: 11
      password: 145686
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

token:
    header: Authorization
    secret: abcdefghijklmnopqrstuvwxyz
    expireTime: 30

mybatis:
    typeAliasesPackage: com.icss.project.**.domain
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enabled: true
  pathMapping: /dev-api

xss:
  enabled: true
  excludes: /system/,/biz/
  urlPatterns: /system/*,/monitor/*,/tool/*

gen:
  author: toto
  packageName: com.icss.project.biz
  autoRemovePre: false
  tablePrefix: sys_
